apiVersion: v1
kind: Pod
metadata:
  name: multitool-client
spec:
  containers:
    - name: multitool
      image: wbitt/network-multitool
      command:
        - /bin/sh
        - -c
        - while true; do sleep 3600; done
